Reverting an earlier rubocop update to solve undefined present?
```
bundle install
./bin/bundle:42:in `gemfile': undefined method `present?' for nil:NilClass (NoMethodError)

    return gemfile if gemfile.present?
                             ^^^^^^^^^
	from ./bin/bundle:84:in `load_bundler!'
	from ./bin/bundle:110:in `<main>'
```